[package]
name = "faer"
version = "0.1.0"
edition = "2021"

[dependencies]
gemm = { version = "0.8", default-features = false }
reborrow = "0.5"
dyn-stack = "0.8"
assert2 = "0.3"
lazy_static = "1.4"
num-traits = "0.2"
aligned-vec = "0.5"
rayon = "1.5"

[features]
default = ["std"]
std = ["gemm/std"]
nightly = ["gemm/nightly"]

[dev-dependencies]
criterion = "0.3"
rand = "0.8.5"
nalgebra = "0.31.0"
assert_approx_eq = "1.1.0"

[[bench]]
name = "bench"
harness = false
